sudo: false

addons:
  chrome: stable

language: java

jdk:
  - oraclejdk9

env:

python:
  - 2.7

before_install:
  - pip install --user codecov
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo chmod +x ~/chromedriver

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - export CHROMEDRIVER_BINARY=~/chromedriver
  - mvn clean install -DskipTests=true -Dchromedriver.binary=~/chromedriver

after_success:
  - codecov
