name: Build 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_js_backend:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [8,10,11,12,13,14]
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-java@v1
       with:
           java-version: ${{ matrix.java }}
     - run: wget https://apt.llvm.org/llvm.sh
     - run: chmod +x llvm.sh
     - run: sudo ./llvm.sh 10
     - run: mvn verify -P jstestsonly
