name: Build 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_js_backend:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [8,10,11,12,13,14]
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-java@v1
       with:
           java-version: ${{ matrix.java }}
     - run: sudo wget https://apt.llvm.org/llvm-snapshot.gpg.key
     - run: sudo apt-key add llvm-snapshot.gpg.key
     - run: sudo add-apt-repository -y "deb http://apt.llvm.org/xenial/   llvm-toolchain-xenial-10  main"
     - run: sudo apt-get -q update
     - run: sudo apt-get install -y clang-10 lldb-10 lld-10 clangd-10
     - run: mvn verify -P jstestsonly
